#ifndef __SQLITE_SPHERE_TYPES__
#define __SQLITE_SPHERE_TYPES__

enum SQLITE_SPHERE_TYPES {
	SQLITE_SPHERE_UNKNOWN = 0,
	SQLITE_SPHERE_POINT = 1,
	SQLITE_SPHERE_EULER = 2,
	SQLITE_SPHERE_CIRCLE = 3,
	SQLITE_SPHERE_LINE = 4,
	SQLITE_SPHERE_ELLIPSE = 5,
	SQLITE_SPHERE_POLYGON = 6,
	SQLITE_SPHERE_PATH = 7,
	SQLITE_SPHERE_BOX = 8
};

#endif